### ISSUE TITLE
Update on Open-Sourcing Frontend Code

### ISSUE THREAD

**Issue by Subashkatel** [google-ai-edge/model-explorer#101]
I know there is already issue #47 about this, but I didn't hear back any response, so I was wondering if the frontend is actually going to be open-sourced or not?
Could you please provide an update on the plans and timeline for open-sourcing the frontend code?

**Comment by pkgoogle** [comment]
Hi @Subashkatel, thank you for your patience. There was a lot of uncertainty around this so I didn't want to communicate anything incorrect w/o some clarity. Currently the expectation is that it is at least 2 months away due to the level of internal only code that we cannot open source. It's effectively a refactor -- so we will open source this eventually. For now I will close this issue as a duplicate and will make this same comment on that issue.

**Comment by Subashkatel** [comment]
Thank you for the response!
